accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView
from django import views as a_view

app_name='accounts'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',views.logout_view,name='logout')
]

cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.view_cart, name='view_cart'),
    path('remove/<int:product_id>',views.remove_from_cart,name='remove'),
    path('remove_item/<int:product_id>',views.decrease_cart_item,name='removeitem'),
    path('checkout/<int:cart_id>',views.checkout,name='checkout'),
    path("order_placed",views.order_placed,name="order_placed"),
    path('order_history/',views.order_history,name='order_history'),
    path('cancel/<int:id>/',views.cancel_order,name='cancel_order'),
    path('cancel_confirmation/<int:id>/',views.cancel_confirmation,name='cancel_confirmation')
]

ecomsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('shop.urls')),
    path('cart/', include('cart.urls')),

]

shop/urls.py
from . import views
from django.urls import path

app_name='shop'
urlpatterns=[
    path('',views.dashboard,name='dashboard'),
    path('detail_view/<int:pk>/',views.detail_view_page,name='detail_view')
]

cart/models.py
from django.db import models
from django.conf import settings
from shop.models import Product
# Create your models here.
class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart ({self.user})" if self.user else "Guest Cart"



class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items' )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} ({self.quantity})({self.cart.user }) in stock{self.product.stock_quantity}"

     

cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from shop.models import Product,Order,OrderItem
from .models import Cart, CartItem


from django.contrib.auth.decorators import login_required

# Create your views here.
 


def _get_session_cart(request):
    return request.session.get('cart', {})


def _save_session_cart(request, cart_data):
    request.session['cart'] = cart_data
    request.session.modified = True


def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_data = _get_session_cart(request)

    if str(product_id) in cart_data:
        cart_data[str(product_id)]['quantity'] += 1
    else:
        cart_data[str(product_id)] = {'quantity': 1}

    _save_session_cart(request, cart_data)

    
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
        if not created:
            cart_item.quantity += 1
        cart_item.save()

    return redirect('cart:view_cart')


def remove_from_cart(request, product_id):
    cart_data = _get_session_cart(request)
    if str(product_id) in cart_data:
        del cart_data[str(product_id)]
    _save_session_cart(request, cart_data)

    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        CartItem.objects.filter(cart=cart, product_id=product_id).delete()

    return redirect('cart:view_cart')


def view_cart(request):
    cart_items = []
    total = 0
    cart_=[]
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        for item in cart.items.select_related('product'):
            total += item.product.price * item.quantity
        cart_items = cart.items.all()
        cart_.append(cart)
        
    else:
        cart_data = _get_session_cart(request)
        for p_id, item in cart_data.items():
            product = get_object_or_404(Product, id=p_id)
            quantity = item['quantity']
            
            total += product.price * quantity
            
            cart_items.append({'product': product, 'quantity': quantity})

    return render(request, 'cart/cart.html', {'cart_items': cart_items, 'total': total,'cart_':cart_})



def decrease_cart_item(request, product_id):
    cart_data = _get_session_cart(request)

    if str(product_id) in cart_data:
        if cart_data[str(product_id)]['quantity'] > 1:
            cart_data[str(product_id)]['quantity'] -= 1
        else:
            del cart_data[str(product_id)]  

        _save_session_cart(request,cart_data)

    if request.user.is_authenticated:
        
        cart = Cart.objects.get(user=request.user)
        cart_item = CartItem.objects.get(cart=cart, product_id=product_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
        

    return redirect('cart:view_cart')
  

def checkout(request,cart_id):
    total=0
    
    cart=Cart.objects.get(id=cart_id)
    product=CartItem.objects.filter(cart_id=cart)
    for item in product:
         total+=item.product.price*item.quantity
          
         
    if request.method=="POST":
              
              name=request.POST.get("name","")
              email=request.POST.get("email","")
              address=request.POST.get("address","")
              city=request.POST.get("city","")
              state=request.POST.get("state","")
              zipcode=request.POST.get("zipcode","")
          
              order=Order(user=request.user,name=name,email=email,address=address,city=city,state=state,zipcode=zipcode)
        
              order.save()


              for item in product:
                   order_item=OrderItem(order=order,product=item.product,quantity=item.quantity,price=item.product.price) 
                 
                   order_item.save()
                   product.delete()   
                    
              return redirect('cart:order_placed')
    return render(request,'cart/checkout.html',{'product':product,'total':total})


def order_placed(request):
    return render(request,"cart/order_placed.html")
 
 


@login_required(login_url='accounts:login')
def order_history(request):
    orders = Order.objects.filter(user=request.user).order_by('-created_at').prefetch_related('items')  # or your related_name
    context = {
        'orders': orders,
    }
    return render(request, 'cart/order_history.html', context)



def cancel_order(request,id):
    order=Order.objects.filter(id=id).delete()
    return redirect('cart:order_history')

def  cancel_confirmation(request,id):
    orders=Order.objects.filter(id=id)
    return render(request,'cart/cancel_confirmation.html',{'orders':orders}) 

cart/templates/cart/cancel_confirmation.html
{%extends 'shop/base.html'%}
{% block content%}


<div class="container mt-5" style="width: 800px;">
    <div class="row text-center">
        <div class="col-12">
            <div><h2>Are you sure you want to cancel the order? </h2> </div>
        </div>
     <div class="row mt-5 text-center" >   
        {%for order in orders %}
        <div class="col-8" style="text-align: center;"><a href="{%url 'cart:cancel_order' order.id %}" class="btn btn-success"> Yes</a></div>
        {%endfor%}
        <div class="col-2" style="text-align: center;"><a href="{%url 'cart:order_history'%}" class="btn btn-danger">No</a></div>
    </div>
    </div>
</div>
{%endblock%}

cart/templates/cart/cart.html
{%extends 'shop/base.html'%}
{% block content%}
<div class="container mt-5">
    <div class="row">
        <h3>Cart Item</h3>
        {%for item in cart_items%}
        <span class="border border-black">

        <div class="col-12">
           <div class="row">
            <div class="col-lg-4 col-12 ps-5">
                <img src="{{item.product.image}}">
            </div>
            <div class="col-lg-5 col-12 my-4">
                
                <h5>{{item.product}}</h5>
                  <h6 style="color: green;">₹ {{item.product.price}}
                 </h6>
                 <div class="row">
                    <div class="col-1"><a class="btn btn-secondary" href="{%url 'cart:removeitem' item.product.pk %}">-</a></div>
                    <div class="col-1 ms-3">{{item.quantity}}</div>
                    <div class="col-1">
                        <a href="{%url 'cart:add_to_cart' item.product.pk %}" class="btn btn-secondary">+</a>

                    </div>
                 </div>
                 <a class="nav-link ps-0" href="{%url 'cart:remove' item.product.pk%}" style="color: red;">Remove</a>
            </div>
           </div>
        </div>
        </span>
        {%endfor%}
    
    </div>
    <div class="row text-end">
        <div class="col-12"  style="font-size: x-large; font-weight: 700;">
         Order Total:   ₹ {{total}}
        </div>
    </div>
    {%if cart_%}
    {%for cart in cart_ %}
    <div class="row text-center my-5">
        <div class="col-12">
         <a class="nav-link btn btn-warning" href="{%url 'cart:checkout' cart.id %}"> Proceed to buy </a>
        </div>
    </div>
    {%endfor%}
    {%else%}
    <div class="row text-center my-5">
        <div class="col-12">
            <a href="{%url 'accounts:login'%}" class="nav-link btn btn-warning">Proceed to buy</a>
        </div>
    </div>
    {%endif%}
</div>
  {%endblock%}

cart/templates/cart/checkout.html
{%extends 'shop/base.html' %}


{% block content%} 

<h2 class="text-center my-4">Checkout page</h2>


 <div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            
            <ul class="list-group ">
                <li class="list-group-item d-flex justify-content-between align-items-center">
    product list
    <span class=" #">Quantity</span>
  </li>
  {% for item in product %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">{{item.product.name}}</div>
      
    </div>
    
    <span class=" ">{{item.quantity}}</span>
  </li>
   {%endfor%}
</ul>

        </div>
         
    </div>
     
  </div>
<div class="container" style="width: 700px;">
    <div class="row text-end ">
        <div class="col-md-12">
           <div style="font-weight: 700; font-size: x-large;"> Total Amount:   ₹{{total}}</div>
        </div>
    </div>
 </div>

<div class="container mt-5 " style="width: 1000px;">
    <div class="row">
        <div class="col-md-12">
            <form class="row g-3" method="post">
                {%csrf_token%}
                <h3 style="text-align: center;">Add Address</h3>
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label">Name</label>
    <input type="text" class="form-control" name="name" id="inputEmail4">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Email</label>
    <input type="text" name="email" class="form-control" id="inputPassword4">
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">Address</label>
    <input type="text" class="form-control" id="inputAddress" name="address" placeholder="1234 Main St">
  </div>
   
  <div class="col-md-6">
    <label for="inputCity" class="form-label">City</label>
    <input type="text" class="form-control" name="city" id="inputCity">
  </div>
  <div class="col-md-4">
    <label for="inputState" class="form-label">State</label>
     <input type="text" class="form-control" name="state" id="inputState">
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Zip</label>
    <input type="text" class="form-control" name="zipcode" id="inputZip">
  </div>

  <div class="col-12">
    <button type="submit" class="btn btn-primary">Place Order</button>
  
</div>
</form>
        </div>
    </div>
</div>

{%endblock%}

cart/templates/cart/order_history.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="container" style="width: 1000px;">
  <h2 class="text-center my-5"> Order History</h2>
 
  <div class="row gy-5 ">
    {%if orders%}
    {%for order in orders %}
<div class="shadow p-3 mb-5 bg-body rounded">

    <div class="col-12">
      <div class="row justify-content-end text-end">
      <div class="col-6">
                  <div><a href="{%url 'cart:cancel_confirmation' order.id %}" class="btn btn-danger">Cancel Order</a></div>
      </div>
      </div>
      <h5>Order Id: #{{order.id}}</h5>
      <h6>Order Placed On : {{order.created_at}}</h6>
      
      <div class="row my-4 gy-4">
        {% for item in order.items.all %}
        <div class="col-2">
        <div ><img src="{{item.product.image}}" style="width: 100px;height: 100px;"></div>
        </div>
        <div class="col-4">
          <h5>{{item.product.name}}</h5>
           Quantity:  {{item.quantity}}
         </div>
         {%endfor%}

      </div>
    </div>
</div>
    {%endfor%}
    {%else%}
    <h2 style="text-align: center;margin-top: 100px;">No orders yet</h2>
    {%endif%}
  </div>
  
</div>
  

   {%endblock%}
 

cart/templates/cart/order_placed.html

    <div style="text-align: center; margin-top: 200px;">
    <h1 style="color: green;">Order Placed Successfully!</h1>
    

    
    <a href="{%url 'shop:dashboard'%}" style="color: black;"> Continue Shopping</a>
    
</div>