accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView
from django import views as a_view

app_name='accounts'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',views.logout_view,name='logout')
]

cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.view_cart, name='view_cart'),
    path('remove/<int:product_id>',views.remove_from_cart,name='remove'),
    path('remove_item/<int:product_id>',views.decrease_cart_item,name='removeitem'),
    path('checkout/<int:cart_id>',views.checkout,name='checkout'),
    path("order_placed",views.order_placed,name="order_placed"),
    path('order_history/',views.order_history,name='order_history'),
    path('cancel/<int:id>/',views.cancel_order,name='cancel_order'),
    path('cancel_confirmation/<int:id>/',views.cancel_confirmation,name='cancel_confirmation')
]

ecomsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('shop.urls')),
    path('cart/', include('cart.urls')),

]

shop/urls.py
from . import views
from django.urls import path

app_name='shop'
urlpatterns=[
    path('',views.dashboard,name='dashboard'),
    path('detail_view/<int:pk>/',views.detail_view_page,name='detail_view')
]

accounts/models.py

# accounts/models.py

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .manager import CustomUserManager

class CustomUser(AbstractBaseUser, PermissionsMixin):
    phone_number = models.CharField(max_length=20, unique=True)
    # other fields as needed
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    first_name=models.CharField(max_length=30,null=True,blank=True)
    last_name=models.CharField(max_length=40,null=True,blank=True)
    email=models.EmailField(null=True,blank=True) 
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = []  # nothing else is required for superuser creation

    objects = CustomUserManager()

    def __str__(self):
        return self.phone_number

accounts/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from django import forms

class Register(UserCreationForm):
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=40)
    email=forms.EmailField()

    class Meta:
        models=CustomUser
        fields=['first_name','last_name','email','phone_number','password1','password2']

accounts/views.py
from django.shortcuts import render,redirect,HttpResponse
from .forms import Register
from django.contrib.auth import logout
from django.contrib  import messages
# Create your views here.
def register(request):
    form=Register(request.POST or None)
    if request.method=='POST':
    
        if form.is_valid():
            print(form.errors)
            user=form.save(commit=True)
            user.is_active=True
            user.save()
            messages.success(request,'Your account has been created successfully!')
            return redirect('accounts:login')
            
    return render(request,'accounts/register.html',{'form':form})        



def logout_view(request):
    
    logout(request)
    return render(request,'accounts/logout.html')

accounts/templates/accounts/login.html
{%extends 'shop/base.html'%}
{%block content%}
<section class="container-fluid">
    <div class="container mt-5">
        <div class="row text-end">
            <div class="col-12">
                <a href="{%url 'shop:dashboard'%}" class="btn btn-secondary">Skip for Now</a>
            </div>
        </div>
        <div class="row row-cols-1 mx-auto" style="width: 20rem;">
            <div class="shadow-lg p-3 mb-5 bg-body rounded">
           <h3 class="text-center">Login</h3>
            <div class="col">
               <form  method="post">
                {%csrf_token%}
                <ul style="background-color:crimson ;">
                 {% for error_list in form.non_field_errors%}
           
               <li >{{error_list}}</li>
          
      {%endfor%}
                </ul>
                <div class="mb-3 mt-5 ">
                    <label for="id_username" class="ps-0">Phone Number</label></br>
                    
                    
                   <input type="text" name="username"  style="width: 18rem;" id="id_username" required>
                </div>
                <div class="mb-3">
                    <label for="id_password" class="ps-0">Password</label></br>
                
                    <input type="password" name="password" style="width: 18rem;" id="id_password">
                </div>
                <div class="mb-3">
                <button type="submit" style="width: 100%;">login</button>
                </div>
                 
                </div>
               </form>
            </div> 
            </div>
        </div>
    </div>
</section>
 
{%endblock%}

accounts/templates/accounts/logout.html
{% extends 'shop/base.html'%}
{% block content%}
<h1 class="text-center mt-5">
    You have been logged out!
</h1>
{%endblock%}

accounts/templates/accounts/register.html
{%extends 'shop/base.html'%}
{% block content%}
<section class="container-fluid">
<div class="container mt-4 ">
 
    <div class="row row-cols-1  mx-auto "style="width: 20rem;">
        <div class="shadow-lg p-3 mb-5 bg-body rounded">

        <h3 class="text-center">Register</h3>
        <div class="col">
            
             <form method="post">
    {% csrf_token%}
        
 {% if form.errors %}

    
      {% for err,error in form.errors.items %}
      <ul style="background-color: crimson;">
      {%for error_list in error%}
        <li >{{ error_list }}</li>
        {%endfor%}
    </ul>
      {% endfor %}
    

  {% endif %}

    <div class="mb-3 mt-5">
    <label for="id_first_name" class="form-label">First Name</label></br>
     <input type="text" name="first_name" style="width: 18rem;"  id="id_first_name" required>
    </div>
    <div class="mb-3">
    <label for="id_last_name" class="form-label">Last Name</label></br>
     <input type="text" name="last_name" style="width: 18rem;" id="id_last_name" required>
    </div>
    <div class="mb-3">
    <label for="id_email" class="form-label">Email</label></br>
    <input type="email" name="email"  style="width: 18rem;" id="id_email" required >
    </div>
    <div class="mb-3">
    <label for="id_phone_number" class="form-label">Phone Number</label></br>
     <input type="text" name="phone_number" style="width: 18rem;"  id="id_phone_number" required>
    </div>
    <div class="mb-3">
    <label for="id_password1" class="form-label">Password</label></br>
     <input type="password" name="password1" style="width: 18rem;" aria-describedby="id_password1_helptext" id="id_password1" required>
    </div>
    <div class="mb-3">
    <label for="id_password2" class="form-label">Confirm Password</label></br>
     <input type="password" name="password2" style="width: 18rem;" aria-describedby="id_password2_helptext" id="id_password2" required>
    </div>
    <div class="mb-3">
    <button type="submit" style="width: 100%;">register</button>
    </div>
   </form> 
     
        </div>
    </div>
    </div>
</div>
</section>

 
 
 
{%endblock%}