accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView
from django import views as a_view

app_name='accounts'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',views.logout_view,name='logout')
]

cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('', views.view_cart, name='view_cart'),
    path('remove/<int:product_id>',views.remove_from_cart,name='remove'),
    path('remove_item/<int:product_id>',views.decrease_cart_item,name='removeitem'),
    path('checkout/<int:cart_id>',views.checkout,name='checkout'),
    path("order_placed",views.order_placed,name="order_placed"),
    path('order_history/',views.order_history,name='order_history'),
    path('cancel/<int:id>/',views.cancel_order,name='cancel_order'),
    path('cancel_confirmation/<int:id>/',views.cancel_confirmation,name='cancel_confirmation')
]

ecomsite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls')),
    path('',include('shop.urls')),
    path('cart/', include('cart.urls')),

]

shop/urls.py
from . import views
from django.urls import path

app_name='shop'
urlpatterns=[
    path('',views.dashboard,name='dashboard'),
    path('detail_view/<int:pk>/',views.detail_view_page,name='detail_view')
]

shop/models.py
from django.db import models
from django.conf import settings
import datetime


# Create your models here.
class Product(models.Model):
    name=models.CharField(max_length=100)
    description=models.TextField()
    price=models.FloatField()
    image=models.CharField(max_length=800)
    category=models.CharField(max_length=200)
    stock_quantity=models.IntegerField()



    def __str__(self):
        return self.name 
    
def today():
    return datetime.datetime.now()
    
 

class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,default=1)
    created_at=models.DateTimeField(default=today,null=True,blank=True)
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    state=models.CharField(max_length=100)
    zipcode=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class OrderItem(models.Model):
    
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.order.name


shop/views.py
from django.shortcuts import render
from .models import Product
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
import re
# Create your views here.


def dashboard(request):
    product=Product.objects.all()

    # search code
    search_item=request.GET.get('item_name' ,'')
    if search_item!=" " and search_item!=None:
        product=product.filter(name__icontains=search_item.strip())

    # paginator code
    pagination=Paginator(product,4)
    page=request.GET.get('page')
    product=pagination.get_page(page)

     


    return render(request,'shop/dashboard.html',{'product':product})


def detail_view_page(request,pk):
    product=Product.objects.get(pk=pk)
    
    return render(request,'shop/detail_view.html',{'product':product})

shop/templates/shop/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" >

     <link rel="stylesheet" href="{% static 'shop/style.css' %}">
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light " style="height: 75px;">
  <div class="container-fluid bg-dark mt-sm-0" >
    <a class="navbar-brand py-4 text-white" href="#">ShopSmart</a>
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation text-white">
      <span class="navbar-toggler-icon "></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a href="{%url 'shop:dashboard'%}" class="nav-link text-white">Home</a>
        </li>
          <li class="nav-item">
          <a href="{%url 'cart:order_history'%}" class="nav-link text-white">Orders</a>
        </li>
          <li class="nav-item">
          <a href="{%url 'cart:view_cart'%}" class="btn btn-secondary">Cart</a>
        </li>
      </ul>
    </div>

    {%if user.is_authenticated %}
     <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white">Wecome {{user.first_name}}!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{%url 'accounts:logout'%}">Logout</a>
        </li>
      </ul>
     </div>
    
    {%else%}
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">

      <ul class="navbar-nav">
        <li class="nav-item">
            <a href="{%url 'accounts:login'%}" class="nav-link text-white">Login</a>
        </li> 
            <li class="nav-item">
          <a class="nav-link text-white" href="{%url 'accounts:register'%}">Register</a>
        </li>
      </ul>
    
    </div>
    {%endif%}
    </div>
  
</nav>

{%for msg in messages %}    
<div style="color: green;text-align: center;font-size: large; font-weight: 700;">{{msg}}</div> 
{%endfor%} 

{%block content%}
{%endblock%}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
 
</body>
 
 </html>

shop/templates/shop/dashboard.html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

</head>
<body>
  

    <nav class="navbar navbar-expand-lg navbar-light bg-light " style="height: 75px;">
  <div class="container-fluid bg-dark mt-sm-0" >
    <a class="navbar-brand py-4 text-white" href="#">ShopSmart</a>
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation text-white">
      <span class="navbar-toggler-icon "></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">

        

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{%url 'shop:dashboard'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{%url 'cart:order_history'%}">Orders</a>
        </li>
        <li class="nav-item">
          <a href="{%url 'cart:view_cart'%}" class="btn btn-secondary">Cart</a>
        </li>
       
      </ul>
    </div>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="nav-link text-white">Welcome {{user.first_name}}!</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{%url 'accounts:logout'%}">logout</a>
            </li>
        </ul>
    </div>

    {%else%}
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white" href="{%url 'accounts:login'%}">Login</a>
        </li>
          <li class="nav-item">
          <a href="{%url 'accounts:register'%}" class="nav-link text-white">register</a>
        </li>
      </ul>
    </div>
{%endif%}
  </div>
    </nav>
<div class="container mt-4">
     
      <form >
            <div class="row justify-content-center gx-0">

         <div class="col-sm-10 col-8">
          <input type="search" placeholder="Search for Products" name="item_name" class="form-control form-control-borderless" >
         </div> 
          <div class="col-sm-1 col-2">
          <button type="submit" class="btn btn-success " >search</button>
          </div>
            </div>
      </form>
      
    
</div>
 <div class="container-fluid">
    
        <div class="container">
        <div class="row row-cols-xl-4 row-cols-lg-3 row-cols-md-2 row-cols-1 mt-5  gy-4 justify-content-center  ">
            {% for item in product%}
            <div class="shadow p-3 mb-5 bg-body rounded">


            <div class="col me-1" >
               <div class="p-4 text-center">
                    <img src="{{item.image}}"alt="" >
               <div id="n{{item.pk}}" style="font-size: x-large;font-weight: 600;">{{item.name}}</div> 
                  <h5 style="color: green;">₹ {{item.price}}</h5>
                  <div class="row gx-0">
                     {%if 5 >= item.stock_quantity and item.stock_quantity != 0%}
                         <p style="color: red;">In stock: only {{item.stock_quantity}} left!</p>
                         <div class="col-6"><a class="btn btn-dark" href="{% url 'shop:detail_view' item.pk%}">View detail</a></div>
                        <div class="col-6"><a id="{{item.pk}}" class="btn atc btn-dark" style="text-align: center;" href="{%url 'cart:add_to_cart' item.pk%}">Add to cart</a></div>
                    {%elif item.stock_quantity == 0%}
                           <p style="color: red;">Out of stock</p>
                           <div class="col-6"><a class="btn btn-dark" href="{%url 'shop:detail_view' item.pk %}">View detail</a></div>
                           <div class="col-6"><a class="btn btn-secondary" style="text-align: center;color: cornsilk;">Add to cart</a></div>
                    {% elif item.stock_quantity > 5 %} 
                          
                            <div class="col-6"><a class="btn btn-dark" href="{%url 'shop:detail_view' item.pk %}">View detail</a></div>
                             <div class="col-6 ">  <a id="{{item.pk}}" class="btn atc btn-dark" style="text-align: center; " href="{%url 'cart:add_to_cart' item.pk%}">Add to cart</a></div>
                    
                       {%endif%}
                  </div>
               </div>
                
        </div>
    </div>
        {%endfor%}
        </div>
        
        
</div>
 <div class="row ">
          <div class="col-md-3 offset-md-4">
            <ul class="pagination justify-content-center">
              {%if product.has_previous %}
              <li class="page_item"><a class="page-link" href="?page={{ product.previous_page_number }}" >Previous</a></li>
              {%endif%}
             <li class="page_item active"><a class="page-link " style="background-color: rgb(34, 39, 42);color: aliceblue;" href="?page={{ product.number}}">Current</a>
            </li>

              {% if product.has_next %}
              <li class="page_item"><a class="page-link" href="?page={{product.next_page_number}}">Next</a> </li>
              {%endif%}
            </ul>
          </div>
        </div>
 </div>

 <div class="container">
  <div class="row">
     {%for item in cart_items%}
      <div class="col">{{item.product}}</div> 
        <div class="col">{{item.quantity}}</div>
        {%endfor%}
  </div>
 </div>
 <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
 
 </html>

shop/templates/shop/detail_view.html
{%extends 'shop/base.html'%}
{% block content%}
    

<div class="container mt-5">
    <div class="row">
        <div class="col-6 ">
            <div class="row" >
                <div class="col-md-12 align-middle" >
                    <img src="{{product.image}}" style="width: 500px; height: 500px;" class="img-fluid">
                </div>
            </div>
               
        </div>
        <div class="col-6">
            <div class="row pt-5">
                <div class="col-md-12">
                    <h1>{{product.name}}</h1>
                    <h2 style="color: green;">Rs. {{product.price}}</h2>
                     <h3>{{product.description}}</h3>

                    {%if 5 >= product.stock_quantity and product.stock_quantity != 0%}
                         <p style="color: red;">In stock: only {{product.stock_quantity}} left!</p>
                         <a class="nav-link" href="{%url 'cart:add_to_cart' product.id%}"  style="background-color: bisque;text-align: center;">Add to cart</a>
                    {%elif product.stock_quantity == 0%}
                           <p style="color: red;">Out of stock</p>
                           <a class="nav-link" style="background-color: darkgray;text-align: center;color: cornsilk;">Add to cart</a>
                    {% elif product.stock_quantity > 5 %} 
            
                           <a class="nav-link " href="{%url 'cart:add_to_cart' product.pk %}" style="background-color: bisque;text-align: center;">Add to cart</a>
                    
                    {%endif%}
                 </div>
            </div>
        </div>
    </div>
</div>

 {%endblock%}






 